### ISSUE TITLE
nodepay app

### ISSUE THREAD

**Issue by doubleTroub1e** [PoPzQ/Wifi-Cashbot#1]
**Is your feature request related to a problem? Please describe.**
There is exist new app same like GRASS, called [Nodepay](https://app.nodepay.ai/register?ref=3iXL7IuXXwKQVE6) (my ref there), it would be really good to add it also here

**Comment by PoPzQ** [comment]
Thanks for the suggestion! We'll add it to the stack.

**Comment by PoPzQ** [comment]
I unfortunately am unable to support this in Wifi-Cashbot as the earnings are below a minimal threshold
